/*1665080202000*/
$(document).ready(function(){try{if(typeof $(".clamp")!=="undefined")$(".clamp").each(function(index,element){$clamp(element,{clamp:4})})}catch(error){console.log(error)}$(window).resize(function(){try{if(typeof $(".clamp")!=="undefined"){$(".clamp").each(function(index,element){$clamp(element,{clamp:"auto"})});$(".clamp").each(function(index,element){$clamp(element,{clamp:4})})}}catch(error){console.log(error)}})});
var secondaryMenuJS={mainMenuCollapseStructure:function(secondaryMenu,test){var $secondaryMenu=$(secondaryMenu);$secondaryMenu.each(function(i,e){var $menuList=$(e).find(".main-menu__list"),$origen=$(e).find(".main-menu__wrapper"),$direction=$(e).find(".nav-dropdown__wrapper");if(!$($menuList).hasClass("js-menu-filters"))var $menuListDetached=$($menuList).detach();else var $menuListDetached="undefined";if(test&&$menuListDetached!="undefined"){$direction.append($menuListDetached);secondaryMenuJS.mainMenuCollapse(secondaryMenu,
test)}else if($menuListDetached!="undefined"){$origen.append($menuListDetached);secondaryMenuJS.mainMenuCollapse(secondaryMenu,test)}})},mainMenuCollapse:function(secondaryMenu,test){$(secondaryMenu).each(function(i,e){var $collapseTrigger=$(e).find(".right-menu__link"),$collapsable=$(e).find(".nav-dropdown");if(test){$($collapsable).removeClass("expand");$($collapseTrigger).removeClass("up");$($collapseTrigger).click(function(){$($collapseTrigger).toggleClass("up");$($collapsable).toggleClass("expand");
if(!$($collapsable).hasClass("expand"))$($collapsable).find(".collapse").collapse("hide");else $($collapsable).find(".collapse").collapse("show")})}else{$($collapsable).removeClass("expand");$($collapseTrigger).removeClass("up");$($collapsable).find(".collapse").collapse("hide");if(!$($collapsable).hasClass("expand"))$($collapsable).addClass("expand")}})},collapseSD:function(collapseSD,test){$(collapseSD).each(function(i,e){var $anchor=$(e).closestDescendant("a"),$menuCollapse=$(e).closestDescendant(".js-menu-collapse"),
menuCollapseID=$($menuCollapse).attr("id"),menuCollapseParent=$(e).parent().attr("class").split(" ")[0],$icon=$(e).closestDescendant(".arrow");if(test){if($icon.length>0)$($icon).attr("data-toggle","collapse").addClass("collapsed").attr("data-target","#"+menuCollapseID).attr("data-parent","."+menuCollapseParent).attr("aria-expanded",false);else $($anchor).attr("data-toggle","collapse").addClass("collapsed").attr("data-target","#"+menuCollapseID).attr("data-parent","."+menuCollapseParent).attr("aria-expanded",
false);$($menuCollapse).addClass("collapse");$($menuCollapse).removeClass("dropdown-menu")}else{$($icon).attr("data-toggle","").removeClass("collapsed").attr("data-target","").attr("data-parent","").attr("aria-expanded","");$($menuCollapse).removeClass("collapse");$($menuCollapse).addClass("dropdown-menu")}})},menuPosition:function(menu){var $menuPosition=$(menu).find(".submenu-position"),$listLinks=$(menu).find(".main-menu__list").find("a"),text="";$($listLinks).each(function(i,e){if($(e).hasClass("active"))text=
$(e).html()});if(!text=="")$($menuPosition).css("display","inline-block").html(text)},subMenuScrollFix:function(jsSubmenu,i){var subMenuWrapper=$(jsSubmenu);var subMenuWrapperPosition=$(subMenuWrapper).offset();var scroll=$(window).scrollTop();if(typeof subMenuWrapperPosition!=="undefined"&&subMenuWrapperPosition.top<scroll)if(!$(subMenuWrapper).hasClass("menu-fixed"))$(subMenuWrapper).addClass("menu-fixed");else{if(i==1&&!$(subMenuWrapper).hasClass("second-submenu")){var offsetTop=$(".js-submenu").eq(0).children().first().height();
$(subMenuWrapper).addClass("second-submenu");$(subMenuWrapper).children().first().css("top",offsetTop)}}else{$(subMenuWrapper).removeClass("menu-fixed");$(subMenuWrapper).removeClass("second-submenu");$(subMenuWrapper).children().first().css("top","")}}};
$(document).ready(function(){var windowWidth=$(window).width();var $secondaryMenu=$("section.menus-secundarios");var $jsSubmenu=$(".js-submenu");var $jsMenuMobile=$(".move-anclas-normal-mobile");var $jsMenuFWMobile=$(".move-anclas-full-width-mobile");var $collapseSD=$($secondaryMenu).find(".js-collapse-sd");var mobileLook=false;secondaryMenuJS.menuPosition($secondaryMenu);if(windowWidth<1199){mobileLook=true;secondaryMenuJS.mainMenuCollapseStructure($secondaryMenu,mobileLook);secondaryMenuJS.collapseSD($collapseSD,
mobileLook)}else{secondaryMenuJS.mainMenuCollapseStructure($secondaryMenu,mobileLook);secondaryMenuJS.collapseSD($collapseSD,mobileLook)}try{$(window).scroll(function(){if(typeof $jsSubmenu!=="undefined")$($jsSubmenu).each(function(i,e){secondaryMenuJS.subMenuScrollFix(e,i)})})}catch(error){console.log(error)}if(windowWidth<1025)try{$(window).scroll(function(){if(typeof $jsMenuMobile!=="undefined")$($jsMenuMobile).each(function(i,e){secondaryMenuJS.subMenuScrollFix(e,i)});if(typeof $jsMenuFWMobile!==
"undefined")$($jsMenuFWMobile).each(function(i,e){secondaryMenuJS.subMenuScrollFix(e,i)})})}catch(error){console.log(error)}});
var menuAnclas={setActiveAndScroll:function(menuAnclas,height){var $listLinks=$(menuAnclas).find(".main-menu-anclas__link");var $html=$(menuAnclas).closest("html");var $body=$(menuAnclas).closest("body");var removeActive=function(list){$(list).each(function(i,e){$(e).removeClass("active")})};var animateScroll=function(url,height){$($html,$body).animate({scrollTop:$(url).offset().top-100},800)};$listLinks.each(function(i,e){var url=$(e).attr("href");$(e).click(function(){var anclaHeight=$(e).closest(".js-header").height();
removeActive($listLinks);$(e).addClass("active");animateScroll(url,anclaHeight)})})},anclaNiceScroll:function(menu){$(menu).find(".row-flex").niceScroll({cursorcolor:"#d0d3d5"}).resize();$(menu).find(".row-flex").dragscrollable({dragSelector:".main-menu-anclas__wrapper",acceptPropagatedEvent:true})}};
$(document).ready(function(){var $menuAncla=$(".menu-anclas");if($(window).width()>1024)try{$($menuAncla).each(function(i,e){menuAnclas.anclaNiceScroll(e)})}catch(error){console.log(error)}try{$($menuAncla).each(function(i,e){menuAnclas.setActiveAndScroll(e)})}catch(error){console.log("try to setActiveAndScroll "+error)}try{$(window).scroll(function(){secondaryMenuJS.subMenuScrollFix($menuAncla)})}catch(error){console.log(error)}if($menuAncla.length>0)$(".nicescroll-rails.nicescroll-rails-vr").remove()});
var userMenuMobile={menuPosition:function(userMM){var $menuPosition=$(userMM).find(".submenu-position"),$listLinks=$(userMM).find(".js-menu-collapse").find("ul li a"),text="";$($listLinks).each(function(i,e){if($(e).hasClass("active"))text=$(e).html()});if(!text=="")$($menuPosition).css("display","inline-block").html(text)}};
$(document).ready(function(){var $userMenuMobile=$(".user-menu-mobile");$userMenuMobile.each(function(i,e){try{userMenuMobile.menuPosition(e)}catch(error){console.log("Try get set menuPosition of active submenu "+error)}})});
var pestanaMenuJS={pestanaSelectInit:function(pestanaWrapper,pestanaMenu,test){$(pestanaWrapper).each(function(i,e){var $collapseTrigger=$(e).find(".right-menu__link"),$collapsable=$(e).find(".nav-dropdown");$(e).find(".tab-content").hide();$(e).find(".tab-content:first").show();$(e).find(".main-menu-pestanas__item:first").find(".main-menu-pestanas__link").addClass("active");pestanaMenuJS.menuPosition(e);$(e).find(".main-menu-pestanas__item").click(function(event){event.preventDefault();$(e).find(".main-menu-pestanas__item").find("a").removeClass("active");
$(this).find("a").addClass("active");$(e).find(".tab-content").hide();var selectTab=$(this).find("a").attr("href");$(selectTab).fadeIn();pestanaMenuJS.menuPosition(e);if(test){$($collapseTrigger).toggleClass("up");$($collapsable).toggleClass("expand");if(!$($collapsable).hasClass("expand"))$($collapsable).find(".collapse").collapse("hide")}})})},pestanaSelect:function(pestanaWrapper,pestanaMenu,test){$(pestanaWrapper).each(function(i,e){var $collapseTrigger=$(e).find(".right-menu__link"),$collapsable=
$(e).find(".nav-dropdown");$(e).find(".tab-content").hide();$(e).find(".main-menu-pestanas__item").click(function(event){event.preventDefault();$(e).find(".main-menu-pestanas__item").find("a").removeClass("active");$(this).find("a").addClass("active");$(e).find(".tab-content").hide();var selectTab=$(this).find("a").attr("href");$(selectTab).fadeIn();if(test){$($collapseTrigger).toggleClass("up");$($collapsable).toggleClass("expand");if(!$($collapsable).hasClass("expand"))$($collapsable).find(".collapse").collapse("hide")}})})},
mainMenuCollapseStructure:function(pestanaMenu,test){var $pestanaMenu=$(pestanaMenu);$pestanaMenu.each(function(i,e){var $menuList=$(e).find(".main-menu-pestanas__list"),$origen=$(e).find(".main-menu-pestanas__wrapper"),$direction=$(e).find(".nav-dropdown__wrapper"),$menuListDetached=$($menuList).detach();if(test){$direction.append($menuListDetached);pestanaMenuJS.mainMenuCollapse(pestanaMenu,test)}else{$origen.append($menuListDetached);pestanaMenuJS.mainMenuCollapse(pestanaMenu,test)}})},mainMenuCollapse:function(pestanaMenu,
test){$(pestanaMenu).each(function(i,e){var $collapseTrigger=$(e).find(".right-menu__link"),$collapsable=$(e).find(".nav-dropdown");if(test){$($collapseTrigger).removeClass("up");$($collapsable).removeClass("expand");$($collapseTrigger).click(function(){$($collapseTrigger).toggleClass("up");$($collapsable).toggleClass("expand");if(!$($collapsable).hasClass("expand"))$($collapsable).find(".collapse").collapse("hide");else $($collapsable).find(".collapse").collapse("show")})}else{$($collapsable).removeClass("expand");
$($collapseTrigger).removeClass("up");$($collapsable).find(".collapse").collapse("hide");if(!$($collapsable).hasClass("expand"))$($collapsable).addClass("expand")}})},collapseSD:function(collapseSD,test){$(collapseSD).each(function(i,e){var $anchor=$(e).closestDescendant("a"),$menuCollapse=$(e).closestDescendant(".js-menu-collapse"),menuCollapseID=$($menuCollapse).attr("id"),menuCollapseParent=$(e).parent().attr("class").split(" ")[0],$icon=$(e).closestDescendant(".arrow");if(test){if($icon.length>
0)$($icon).attr("data-toggle","collapse").addClass("collapsed").attr("data-target","#"+menuCollapseID).attr("data-parent","."+menuCollapseParent).attr("aria-expanded",false);else $($anchor).attr("data-toggle","collapse").addClass("collapsed").attr("data-target","#"+menuCollapseID).attr("data-parent","."+menuCollapseParent).attr("aria-expanded",false);$($menuCollapse).addClass("collapse");$($menuCollapse).removeClass("dropdown-menu")}else{$($icon).attr("data-toggle","").removeClass("collapsed").attr("data-target",
"").attr("data-parent","").attr("aria-expanded","");$($menuCollapse).removeClass("collapse");$($menuCollapse).addClass("dropdown-menu")}})},menuPosition:function(menu){var $menuPosition=$(menu).find(".submenu-position"),$listLinks=$(menu).find(".main-menu-pestanas__link"),text="";$($listLinks).each(function(i,e){if($(e).hasClass("active"))text=$(e).html()});if(!text=="")$($menuPosition).css("display","inline-block").html(text)},subMenuScrollFix:function(jsSubmenu,i){var subMenuWrapper=$(jsSubmenu);
var subMenuWrapperPosition=$(subMenuWrapper).offset();var scroll=$(window).scrollTop();if(typeof subMenuWrapperPosition!=="undefined"&&subMenuWrapperPosition.top<scroll)if(!$(subMenuWrapper).hasClass("menu-fixed"))$(subMenuWrapper).addClass("menu-fixed");else{if(i==1&&!$(subMenuWrapper).hasClass("second-submenu"))$(subMenuWrapper).addClass("second-submenu")}else{$(subMenuWrapper).removeClass("menu-fixed");$(subMenuWrapper).removeClass("second-submenu")}}};
$(document).ready(function(){$("[data-lazy-image]").each(function(){var lazy=$(this).data("lazy-image"),value=$(this).attr("src");if(!value&&lazy)$(this).attr("src",lazy)});$("[data-lazybck-image]").each(function(){var lazy=$(this).data("lazybck-image"),value=$(this).css("background-image");if(!value&&lazy)$(this).css("background-image","url("+lazy+")")});$("[data-lazy-css]").each(function(){var lazy=$(this).data("lazy-css");if(lazy&&!$(this).hasClass(lazy))$(this).addClass(lazy)})});
$(document).ready(function(){var windowWidth=$(window).width();var $pestanaWrapper=$(".menu-pestanas-wrapper");var $pestanaMenu=$("section.menu-pestanas");var $jsSubmenu=$(".js-submenu");var $collapseSD=$($pestanaMenu).find(".js-collapse-sd");var mobileLook=false;if(windowWidth<992){mobileLook=true;pestanaMenuJS.pestanaSelectInit($pestanaWrapper,$pestanaMenu,mobileLook);pestanaMenuJS.mainMenuCollapseStructure($pestanaMenu,mobileLook);pestanaMenuJS.collapseSD($collapseSD,mobileLook)}else{pestanaMenuJS.pestanaSelectInit($pestanaWrapper,
$pestanaMenu,mobileLook);pestanaMenuJS.mainMenuCollapseStructure($pestanaMenu,mobileLook);pestanaMenuJS.collapseSD($collapseSD,mobileLook)}try{$(window).scroll(function(){$($jsSubmenu).each(function(i,e){if(e.length>0)pestanaMenuJS.subMenuScrollFix(e,i)})})}catch(error){console.log(error)}var initWidth=$(window).width();$(window).resize(function(){if($(this).width()!=initWidth){var windowWidth=$(window).width();var $pestanaWrapper=$(".menu-pestanas-wrapper");var $pestanaMenu=$("section.menu-pestanas");
var $collapseSD=$($pestanaMenu).find(".js-collapse-sd");var mobileLook=false;if(windowWidth<992){mobileLook=true;pestanaMenuJS.pestanaSelect($pestanaWrapper,$pestanaMenu,mobileLook);pestanaMenuJS.mainMenuCollapseStructure($pestanaMenu,mobileLook);pestanaMenuJS.collapseSD($collapseSD,mobileLook)}else{pestanaMenuJS.pestanaSelect($pestanaWrapper,$pestanaMenu,mobileLook);pestanaMenuJS.mainMenuCollapseStructure($pestanaMenu,mobileLook);pestanaMenuJS.collapseSD($collapseSD,mobileLook)}}})});
var cabDestacada={setHeight:function($destacada){var headerHeight=$($destacada).closest("body").find("header").height();$($destacada).each(function(){if(!$(this).hasClass("autoHeight"))$(this).find(".jumbotron").css("height","calc(100vh - "+headerHeight+"px)")})},clear:function($cabDestacada){if($($cabDestacada).find(".slick-prev").length>0)$($cabDestacada).find(".slick-prev").html("");if($($cabDestacada).find(".slick-next").length>0)$($cabDestacada).find(".slick-next").html("");if($($cabDestacada).find(".slider-counter").length>
0)$($cabDestacada).find(".slider-counter").each(function(i,e){$(e).remove()})},encapsulateDots:function($cabDestacada){$($cabDestacada).each(function(i,e){var $dots=$(e).find(".slick-dots");$dots.before("\x3cdiv class\x3d'dots-wrapper'\x3e\x3c/div\x3e");var detached=$dots.detach();$(detached).appendTo($(e).find(".dots-wrapper"));if($($dots).find("li").length<2)$(e).find(".dots-wrapper").hide()})},getPrevTitle:function($cabDestacada,actual){var prevTitle=$($cabDestacada).closest(".cabecera-destacada").data("txtprev");
var previous=actual-1;var $slidePrev=$($cabDestacada).find('*[data-slick-index\x3d"'+previous+'"]');if($slidePrev.data("title")!="")prevTitle=$slidePrev.data("title");return prevTitle},getNextTitle:function($cabDestacada,actual){var nextTitle=$($cabDestacada).closest(".cabecera-destacada").data("txtnext");var next=actual+1;var $slideNext=$($cabDestacada).find('*[data-slick-index\x3d"'+next+'"]');if($slideNext.data("title")!="")nextTitle=$slideNext.data("title");return nextTitle},addTitles:function($cabDestacada,
actual){var titlePrev=cabDestacada.getPrevTitle($cabDestacada,actual);var titleNext=cabDestacada.getNextTitle($cabDestacada,actual);var $prev=$($cabDestacada).find(".slick-prev");var $next=$($cabDestacada).find(".slick-next");$prev.append("\x3cspan\x3e"+titlePrev+"\x3c/span\x3e");$next.append("\x3cspan\x3e"+titleNext+"\x3c/span\x3e")},slideCounter:function($cabDestacada,actual,total){actual=actual+1;var $dots=$($cabDestacada).find(".slick-dots");if(actual<10)$dots.before("\x3cspan class\x3d'actual slider-counter'\x3e0"+
actual+"\x3c/span\x3e");else $dots.before("\x3cspan class\x3d'actual slider-counter'\x3e"+actual+"\x3c/span\x3e");if(total<10)$dots.after("\x3cspan class\x3d'total slider-counter'\x3e0"+total+"\x3c/span\x3e");else $dots.after("\x3cspan class\x3d'total slider-counter'\x3e"+total+"\x3c/span\x3e")},noVideoMobile:function($cabDestacada){var video=$($cabDestacada).find(".video-wrapper-loop").find("video");var iframe=$($cabDestacada).find(".video-wrapper-loop").find("iframe");$(video).find("source").each(function(i,
e){$(e).attr("src","")});$(iframe).attr("src","")},navButtonsMovil:function($cabDestacada,isMovil){if($($cabDestacada).find(".containerNavButtonMovil").length==0&&isMovil!="undefined"){var $next=$($cabDestacada).find(".slick-next").detach();var $prev=$($cabDestacada).find(".slick-prev").detach();var spanNavButton='\x3cspan class\x3d"containerNavButtonMovil"\x3e\x3c/span\x3e';$($cabDestacada).find(".dots-wrapper").append(spanNavButton);$($cabDestacada).find(".containerNavButtonMovil").append($prev).append($next)}else;
if(isMovil=="isMovil"){var spanNavButtonDetached=$($cabDestacada).find(".containerNavButtonMovil").detach();$($cabDestacada).find(".dots-wrapper").append(spanNavButtonDetached)}if(isMovil=="isTablet"){var spanNavButtonDetached=$($cabDestacada).find(".containerNavButtonMovil").detach();$($cabDestacada).find(".dots-wrapper").prepend(spanNavButtonDetached)}},init:function($cabDestacada,actual,total,isMovil){cabDestacada.clear($cabDestacada);cabDestacada.encapsulateDots($cabDestacada);cabDestacada.slideCounter($cabDestacada,
actual,total);cabDestacada.navButtonsMovil($cabDestacada,isMovil);cabDestacada.addTitles($cabDestacada,actual)},render:function($cabDestacada,actual,total){cabDestacada.clear($cabDestacada);cabDestacada.slideCounter($cabDestacada,actual,total);cabDestacada.addTitles($cabDestacada,actual)}};
document.addEventListener("DOMContentLoaded",()=>{const checkNumberLineChild=()=>{const highlightedSliderCelite=document.querySelectorAll(".cabecera-destacada-celite");if(highlightedSliderCelite)highlightedSliderCelite.forEach((slider)=>{function checkTopNumber(){if(slider.firstElementChild.classList.contains("number-line")&&slider.firstElementChild.classList.contains("top-top"))slider.classList.add("has-top-number");else slider.classList.remove("has-top-number")}function checkBottomNumber(){if(slider.lastElementChild.classList.contains("number-line")&&
slider.lastElementChild.classList.contains("bottom-bottom"))slider.classList.add("has-bottom-number");else slider.classList.remove("has-bottom-number")}checkTopNumber();checkBottomNumber()});const highlightedSlider=document.querySelectorAll(".cabecera-destacada");if(highlightedSlider)highlightedSlider.forEach((slider)=>{function checkTopNumber(){if(slider.firstElementChild.classList.contains("number-line")&&slider.firstElementChild.classList.contains("top-top"))slider.classList.add("has-top-number");
else slider.classList.remove("has-top-number")}function checkBottomNumber(){if(slider.lastElementChild.classList.contains("number-line")&&slider.lastElementChild.classList.contains("bottom-bottom"))slider.classList.add("has-bottom-number");else slider.classList.remove("has-bottom-number")}checkTopNumber();checkBottomNumber()});const productDistributor=document.querySelectorAll(".producto-distribuidor");if(productDistributor)productDistributor.forEach((slider)=>{function checkTopNumber(){if(slider.firstElementChild.classList.contains("number-line")&&
slider.firstElementChild.classList.contains("top-top"))slider.classList.add("has-top-number");else slider.classList.remove("has-top-number")}function checkBottomNumber(){if(slider.lastElementChild.classList.contains("number-line")&&slider.lastElementChild.classList.contains("bottom-bottom"))slider.classList.add("has-bottom-number");else slider.classList.remove("has-bottom-number")}checkTopNumber();checkBottomNumber()})};function hideNumberLines(){const numbersLine=document.querySelectorAll(".number-line");
const numberLine=numbersLine.forEach((number)=>{if(number.textContent==="")number.style.setProperty("--display","none")})}checkNumberLineChild();hideNumberLines()});
$(document).ready(function(){var direction;var useRtl=false;document.dir!=undefined?direction=document.dir:direction=document.getElementsByTagName("html")[0].getAttribute("dir");if(direction=="rtl")useRtl=true;try{var hasThumbnailSlider=function(el){var itHas=$(el).closest(".cabecera-destacada").find(".js-slider-thumbnails").length>0;return itHas}}catch(error){console.log(error)}try{var $cabeceraDest=$(".cabecera-destacada").eq(0);cabDestacada.setHeight($cabeceraDest)}catch(error){console.log("setting cabecera destacada height, got this error "+
error)}try{$(".js-slider-cabecera").each(function(i,e){var total=0;var current=0;$(e).on("init",function(event,slick,currentSlide,nextSlide){total=slick.slideCount;current=0});if(hasThumbnailSlider(e)){$(e).not(".slick-initialized").slick({dots:true,speed:300,rtl:useRtl,asNavFor:".js-slider-thumbnails"});$(e).closest(".cabecera-destacada").find(".js-slider-thumbnails").not(".slick-initialized").slick({slidesToShow:7,swipeToSlide:true,arrows:false,dots:false,rtl:useRtl,centerMode:true,asNavFor:".js-slider-cabecera",
focusOnSelect:true,responsive:[{breakpoint:1024,settings:"unslick"}]})}else $(e).not(".slick-initialized").slick({dots:true,rtl:useRtl,speed:300});var isMovil="undefined";if($(window).width()>991&&$(window).width()<1199)isMovil="isTablet";else if($(window).width()<991)isMovil="isMovil";cabDestacada.init(e,current,total,isMovil)})}catch(error){console.log("init slider cabecera destacada "+error)}try{$(".js-slider-cabecera").each(function(i,e){$(e).on("afterChange",function(event,slick,currentSlide,
nextSlide){var total=slick.slideCount;cabDestacada.render(e,currentSlide,total);var scrollElement=$(".js-center-scroll");commons.centerScroll(scrollElement)})})}catch(error){console.log("on change slider cabecera destacada "+error)}try{var $cabeceraDest=$(".cabecera-destacada");if($(window).width()<1024)cabDestacada.noVideoMobile($cabeceraDest)}catch(error){console.log("video bg mobile "+error)}});
$(window).resize(function(){try{var $cabeceraDest=$(".cabecera-destacada");$($cabeceraDest).each(function(){cabDestacada.setHeight(this)})}catch(error){console.log("setting cabecera destacada height, got this error "+error)}try{if($(window).width()<1199)$(".cabecera-destacada").each(function(i,e){var isMovil="undefined";if($(window).width()>991&&$(window).width()<1199)isMovil="isTablet";else if($(window).width()<991)isMovil="isMovil";cabDestacada.navButtonsMovil(e,isMovil)})}catch(error){console.log(error)}});
$(document).ready(function(){$(".product-detail-manual  .slick-dots").appendTo(".product-detail-manual .move-slick-dots")});$(document).ready(function(){$(".product-detail-full-width  .slick-dots").appendTo(".product-detail-full-width .move-slick-dots")});
$(document).ready(function(){function moveAnclas(){if($(window).width()<992){if($(".menu-anclas.transparent-theme").length>0)$(".menu-anclas.transparent-theme").appendTo(".product-detail-manual  .move-anclas");if($(".menu-anclas.white-theme").length>0)$(".menu-anclas.white-theme").appendTo(".product-detail .move-anclas-normal-mobile");if($(".list-actions").length>0)$(".list-actions").appendTo(".move-list-action-mobile")}else{if($(".menu-anclas.transparent-theme").length>0)$(".menu-anclas.transparent-theme").appendTo(".menudesktop");
if($(".menu-anclas.white-theme").length>0){var $submenu=$();$(".js-submenu").each(function(){if($(this).closest(".js-header").length<1)$submenu=$(this)});$(".menu-anclas.white-theme").appendTo($submenu)}if($(".list-actions").length>0)$(".list-actions").appendTo(".menu-anclas .right-menu__wrapper")}}moveAnclas();$(window).resize(moveAnclas)});
$(document).ready(function(){function moveBreadcrumbFull(){var contenedor="\x3cdiv class\x3d'container container-helper'\x3e\x3c/div\x3e";if($(window).width()<992)if($(".move-breadcrumb-mobile").length>0&&$(".breadcrumb.full-width").length>0)$(" .breadcrumb.full-width").appendTo(".move-breadcrumb-mobile");else{if($(".breadcrumb.full-width").length>0&&$(".container-helper .breadcrumb.full-width").length<1){$(".container-helper").remove();$("header").after(contenedor);$(".breadcrumb.full-width").appendTo(".container-helper")}}else if($(".breadcrumb.full-width").length>
0){$(" .breadcrumb.full-width").appendTo(".breadcrumb-desktop");$(".container-helper").remove()}}moveBreadcrumbFull();$(window).resize(moveBreadcrumbFull)});
$(document).ready(function(){function moveBreadcrumb(){var contenedor="\x3cdiv class\x3d'container container-helper'\x3e\x3c/div\x3e";if($(window).width()<992)if($(".move-breadcrumb-mobile").length>0&&$(" .breadcrumb.normal").length>0)$(".breadcrumb.normal").appendTo(".move-breadcrumb-mobile");else{if($(" .breadcrumb.normal").length>0&&$(".container-helper .breadcrumb.normal").length<1){$("header").after(contenedor);$(" .breadcrumb.normal").appendTo(".container-helper")}}else if($(" .breadcrumb.normal").length>
0){$(".breadcrumb.normal").prependTo(".product-card.options");$(".container-helper").remove()}}moveBreadcrumb();$(window).resize(moveBreadcrumb)});$(document).ready(function(){function moveDiv(){if($(window).width()<992)$(".menu-anclas.white-theme").prependTo(" .move-anclas-full-width-mobile")}moveDiv();$(window).resize(moveDiv)});
$(document).ready(function(){function moveDiv(){if($(window).width()<992)if($(".move-product-navigation-full-width-mobile").length>0&&$(".product_navigation").length>0)$(".product_navigation").appendTo(" .move-product-navigation-full-width-mobile")}moveDiv();$(window).resize(moveDiv)});
var hotspots={clear:function($hotspots){var $slide=$($hotspots).find(".hotspots-slide");var $pointLink=$($hotspots).find(".hotspots-points").find(".point");$slide.each(function(i,e){$(e).removeClass("show")});$pointLink.each(function(i,e){$(e).parent().removeClass("active")})},showSlide:function($hotspots,dataShow){var $slide=$($hotspots).find(".hotspots-slide");$slide.each(function(i,e){var slideId="#"+$(e).attr("id");if(slideId==dataShow){$(e).addClass("show");hotspots.dataSlideSetter($hotspots,
i)}})},initSlide:function($hotspots){var $slide=$($hotspots).find(".hotspots-slide");var $pointList=$($hotspots).find(".hotspots-points").find("a");var dataShow=$pointList.first().attr("data-show");$pointList.each(function(i,e){if(i==0){hotspots.showSlide($hotspots,dataShow);$(e).addClass("active")}});$slide.each(function(i,e){$(e).find(".js-close").click(function(){hotspots.clear($hotspots);hotspots.dataSlideSetter($hotspots,0)})})},setup:function($hotspots){var $image=$($hotspots).find(".hotspot-overflow").closestDescendant("img");
var $list=$($hotspots).find(".hotspots-points");var width=$image.width();$list.width(width)},activate:function($hotspots){var $pointLink=$($hotspots).find(".hotspots-points").find(".point");var dataShow="";$pointLink.each(function(i,e){$(e).click(function(i,el){var $el=$(this);dataShow=$($el).parent().attr("data-show");if($($el).parent().hasClass("active"))try{hotspots.clear($hotspots)}catch(error){console.log("clear hotspots got this "+error)}else{try{hotspots.clear($hotspots)}catch(error){console.log("clear hotspots got this "+
error)}try{$($el).parent().addClass("active");hotspots.showSlide($hotspots,dataShow)}catch(error){console.log("show slide hotspots got this "+error)}}})})},dataSlideSetter:function($hotspots,index){$($hotspots).find(".hotspots-sliders-arrows").attr("data-slide",index)},arrows:function($hotspots){var $arrowLeft=$($hotspots).find(".arrow-left");var $arrowRight=$($hotspots).find(".arrow-right");var actualSlide=$($hotspots).find(".hotspots-sliders-arrows").data("slide");var $pointList=$($hotspots).find(".hotspots-points").find("a");
var slidesLength=$($hotspots).find(".hotspots-points").find("a").length;var displaySlide=function(i){var $elem=$pointList.get(i);var dataShow=$($elem).data("show");hotspots.clear($hotspots);$($elem).addClass("active");hotspots.showSlide($hotspots,dataShow)};$arrowLeft.click(function(){actualSlide--;if(actualSlide<0)actualSlide=slidesLength-1;displaySlide(actualSlide)});$arrowRight.click(function(){actualSlide++;if(actualSlide>slidesLength-1)actualSlide=0;displaySlide(actualSlide)})},init:function($hotspots){hotspots.setup($hotspots);
hotspots.initSlide($hotspots);hotspots.activate($hotspots);hotspots.arrows($hotspots)},render:function($hotspots){hotspots.clear($hotspots);hotspots.setup($hotspots)},renderResize:function($hotspots){hotspots.setup($hotspots)}};$.fn.isInViewport=function(){var elementTop=$(this).offset().top;var elementBottom=elementTop+$(this).outerHeight();var viewportTop=$(window).scrollTop();var viewportBottom=viewportTop+100;return elementBottom>viewportTop&&elementTop<viewportBottom};
$(window).on("resize scroll",function(){$(".hotspots").each(function(){if($(this).isInViewport()){$(this).removeClass("anime-shake");$(this).addClass("anime-shake")}else $(this).removeClass("anime-shake")})});$(document).ready(function(){var $hotspots=$(".hotspots");$hotspots.each(function(i,e){try{hotspots.init(e)}catch(error){console.log("init hotspots got this error "+error)}})});
$(window).resize(function(){var $hotspots=$(".hotspots");$hotspots.each(function(i,e){try{hotspots.renderResize(e)}catch(error){console.log("init hotspots got this error "+error)}})});
$(document).ready(function(){try{var direction;var useRtl=false;document.dir!=undefined?direction=document.dir:direction=document.getElementsByTagName("html")[0].getAttribute("dir");if(direction=="rtl")useRtl=true;if($(".js-slider-blog").length>0)$(".js-slider-blog").each(function(i,slider){var blogSlidercols=$(slider).data("col");$(slider).not(".slick-initialized").slick({dots:true,arrow:false,swipeToSlide:true,rtl:useRtl,infinite:false,speed:300,slidesToShow:blogSlidercols,responsive:[{breakpoint:991,
settings:{dots:false,rtl:useRtl}},{breakpoint:767,settings:{dots:false,slidesToShow:1,rtl:useRtl}}]})})}catch(error){console.log("Try set slider blog got "+error)}});
var colectionSlider={clear:function($colectionSlider){if($($colectionSlider).closest(".slider-blog").find(".counter-sit").length>0)$($colectionSlider).closest(".slider-blog").find(".slider-counter").each(function(i,e){$(e).remove()})},slideCounter:function($colectionSlider,actual,total){actual=actual+1;var $counter=$($colectionSlider).closest(".slider-blog").find(".counter-sit");if(total>1){if(actual<10)$counter.append("\x3cspan class\x3d'actual slider-counter'\x3e0"+actual+"\x3c/span\x3e");else $counter.append("\x3cspan class\x3d'actual slider-counter'\x3e"+
actual+"\x3c/span\x3e");if(total<10)$counter.append("\x3cspan class\x3d'total slider-counter'\x3e0"+total+"\x3c/span\x3e");else $counter.append("\x3cspan class\x3d'total slider-counter'\x3e"+total+"\x3c/span\x3e")}},init:function($colectionSlider,actual,total){colectionSlider.clear($colectionSlider);colectionSlider.slideCounter($colectionSlider,actual,total)},render:function($colectionSlider,actual,total){colectionSlider.clear($colectionSlider);colectionSlider.slideCounter($colectionSlider,actual,
total)}};
var collectionSlider={clear:function($collectionSlider){if($($collectionSlider).closest(".slider-blog").find(".counter-sit").length>0)$($collectionSlider).closest(".slider-blog").find(".slider-counter").each(function(i,e){$(e).remove()})},slideCounter:function($collectionSlider,actual,total){actual=actual+1;var $counter=$($collectionSlider).closest(".slider-blog").find(".counter-sit");if(total>1){if(actual<10)$counter.append("\x3cspan class\x3d'actual slider-counter'\x3e0"+actual+"\x3c/span\x3e");else $counter.append("\x3cspan class\x3d'actual slider-counter'\x3e"+
actual+"\x3c/span\x3e");if(total<10)$counter.append("\x3cspan class\x3d'total slider-counter'\x3e0"+total+"\x3c/span\x3e");else $counter.append("\x3cspan class\x3d'total slider-counter'\x3e"+total+"\x3c/span\x3e")}},init:function($collectionSlider,actual,total){colectionSlider.clear($collectionSlider);colectionSlider.slideCounter($collectionSlider,actual,total)},render:function($collectionSlider,actual,total){colectionSlider.clear($collectionSlider);colectionSlider.slideCounter($collectionSlider,
actual,total)}};
$(document).ready(function(){var direction;var useRtl=false;document.dir!=undefined?direction=document.dir:direction=document.getElementsByTagName("html")[0].getAttribute("dir");if(direction=="rtl")useRtl=true;try{$(".js-slider-coleccion").each(function(i,e){var total=0;var current=0;$(e).on("init",function(event,slick,currentSlide,nextSlide){total=slick.slideCount;current=0});$(e).not(".slick-initialized").slick({dots:true,arrow:false,infinite:false,rtl:useRtl,speed:300,slidesToShow:1,swipeToSlide:true,
touchThreshold:10,responsive:[{breakpoint:991,settings:{dots:false,rtl:useRtl}},{breakpoint:767,settings:{dots:false,slidesToShow:1,rtl:useRtl}}]});colectionSlider.init(e,current,total)})}catch(error){console.log("init slider colection "+error)}try{$(".js-slider-coleccion").each(function(i,e){$(e).on("afterChange",function(event,slick,currentSlide,nextSlide){var total=slick.slideCount;colectionSlider.render(e,currentSlide,total)})})}catch(error){console.log("on change slider colection "+error)}});
$(document).ready(function(){try{$(".js-slider-coleccion2").each(function(i,e){var total=0;var current=0;$(e).on("init",function(event,slick,currentSlide,nextSlide){total=slick.slideCount;current=0});$(e).not(".slick-initialized").slick({dots:true,arrow:false,infinite:false,speed:300,touchThreshold:10,slidesToShow:1,responsive:[{breakpoint:991,settings:{dots:false}},{breakpoint:767,settings:{dots:false,slidesToShow:1}}]});colectionSlider.init(e,current,total)})}catch(error){console.log("init slider colection "+
error)}try{$(".js-slider-coleccion2").each(function(i,e){$(e).on("afterChange",function(event,slick,currentSlide,nextSlide){var total=slick.slideCount;colectionSlider.render(e,currentSlide,total)})})}catch(error){console.log("on change slider colection "+error)}try{$(".js-slider-collection").each(function(i,e){var total=0;var current=0;var sliderCols=$(e).data("col");$(e).on("init",function(event,slick,currentSlide,nextSlide){total=slick.slideCount;current=0;const currentSlideText=$(".js-slider-collection .slick-current.slick-active").find(".image-blog").data("text");
const collectionSliderTitle=document.querySelector(".title-link");collectionSliderTitle.textContent=currentSlideText});$(e).slick({dots:true,arrow:false,infinite:true,speed:300,touchThreshold:10,slidesToScroll:1,slidesToShow:sliderCols,responsive:[{breakpoint:991,settings:{dots:false}},{breakpoint:767,settings:{dots:false,slidesToShow:1}}]});colectionSlider.init(e,current,total)})}catch(error){console.log("on change slider colection "+error)}try{$(".js-slider-collection").each(function(i,e){$(e).on("afterChange",
function(event,slick,currentSlide,nextSlide){var total=slick.slideCount;colectionSlider.render(e,currentSlide,total)});$(e).on("afterChange",function(event,slick,currentSlide,nextSlide){const currentSlideText=$(".js-slider-collection .slick-current.slick-active").find(".image-blog").data("text");const collectionSliderTitle=document.querySelector(".title-link");collectionSliderTitle.textContent=currentSlideText})})}catch(error){console.log("on change slider colection "+error)}try{$("#modal-image-lightbox").on("show.bs.modal",
function(event){var button=$(event.relatedTarget);var image=button.data("image");var modal=$(this);modal.find(".modal-image-lightbox").attr("src",image)})}catch(error){console.log("on change slider colection "+error)}});
var product={selectColor:function(productEl,device){$(productEl).each(function(i,e){var hasColor=$(e).find(".colors");if(hasColor.length>0)$(e).find(".colors").find("button").each(function(index,el){if(index==0){$(el).addClass("selected");var elPvp=$(el).attr("data-pvp");if(elPvp)$(el).closest(".wrapper-producto").find(".price").html(elPvp);product.selectImg(e,this,device)}$(el).click(function(){$(this).addClass("selected").siblings().removeClass("selected");var elPvp=$(el).attr("data-pvp");if(elPvp)$(this).closest(".wrapper-producto").find(".price").html(elPvp);
var novelty=$(el).attr("data-novelty");if(novelty==="true")$(this).closest(".wrapper-producto").find(".promo li.black").show();else $(this).closest(".wrapper-producto").find(".promo li.black").hide();var discontinued=$(el).attr("data-discontinued");if(discontinued==="true")$(this).closest(".wrapper-producto").parent().find(".sold-out").show();else $(this).closest(".wrapper-producto").parent().find(".sold-out").hide();product.selectImg(e,this,device)})});else return false})},selectImg:function(productEl,
colorSelected,device,indexSelected){var imageName=$(colorSelected).data("image");var isLiferay=$(productEl).closest(".js-isLiferay");if(imageName&&imageName.length>0){switch(device){case "mobile":imageName=$(colorSelected).data("sm-image");break;default:imageName=$(colorSelected).data("image")}if(isLiferay.length>0){var imgeUrl=$(productEl).find(".wrapper-img").css("background-image");var imgeUrlSplited=imgeUrl.substring(0,imgeUrl.lastIndexOf("("));var imgeFinalUrl=imgeUrlSplited+'("'+imageName+'")'}else{var imgeUrl=
$(productEl).find(".wrapper-img").css("background-image");var imgeUrlSplited=imgeUrl.substring(0,imgeUrl.lastIndexOf("/"));var imgeFinalUrl=imgeUrlSplited+"/"+imageName+'")'}$(productEl).find(".wrapper-img").css("background-image",imgeFinalUrl)}else return false},applyMatchHeight:function(productEl){var text=$(productEl).find(".title-producto");var finish=$(productEl).find(".colors");var dades=$(productEl).find(".dades");var collection=$(productEl).find(".coleccion");$(text).matchHeight();$(finish).matchHeight();
$(dades).matchHeight();$(collection).matchHeight()},clear:function(productEl){$(productEl).each(function(i,e){var hasColor=$(e).find(".colors");if(hasColor.length>0)$(e).find(".colors").find("button").each(function(index,el){$(this).removeClass("selected");if(index==0){$(this).addClass("selected");product.selectImg(e,this)}})})}};
$(document).ready(function(){var $product=$(".wrapper-producto");var windowWidth=$(window).width();var device="desktop";if(windowWidth<768)device="mobile";try{$product.each(function(i,e){product.selectColor(e,device)})}catch(error){console.log(error)}try{if($(".js-slider-producto").length>0)$(".js-slider-producto").each(function(i,slider){var sliderProductCols=$(slider).data("col");$(slider).on("init",function(event,slick){product.applyMatchHeight($product)});$(slider).on("reInit",function(event,
slick){product.applyMatchHeight($product)});$(slider).not(".slick-initialized").slick({dots:true,arrow:false,slidesToShow:sliderProductCols,infinite:false,speed:300,touchThreshold:10,centerMode:false,slidesToScroll:2,responsive:[{breakpoint:1199,settings:{dots:true,slidesToShow:3}},{breakpoint:991,settings:{dots:false,slidesToShow:2,slidesToScroll:1}},{breakpoint:767,settings:{dots:false,slidesToShow:1,slidesToScroll:1}}]}).on("setPosition",function(event,slick){slick.$slides.css("height",slick.$slideTrack.height()+
"px")})})}catch(error){console.log("Try set slider product got "+error)}try{if($(".js-slider-producto-vertical").length>0)$(".js-slider-producto-vertical").each(function(i,slider){var sliderProductCols=$(slider).data("col");$(slider).on("init",function(event,slick){product.applyMatchHeight($product)});$(slider).on("reInit",function(event,slick){product.applyMatchHeight($product)});$(slider).slick({dots:true,arrow:false,infinite:false,speed:300,touchThreshold:10,centerMode:false,slidesToShow:sliderProductCols,
slidesToScroll:2,responsive:[{breakpoint:1200,settings:{dots:true,slidesToShow:2}},{breakpoint:992,settings:{dots:true,slidesToShow:2,slidesToScroll:1}},{breakpoint:767,settings:{dots:true,slidesToShow:2,slidesToScroll:1}}]}).on("setPosition",function(event,slick){slick.$slides.css("height",slick.$slideTrack.height()+"px")})})}catch(error){console.log("Try set slider product got "+error)}});
var productCard={activateCard:function($productCard){$($productCard).find(".js-activate").click(function(){$(this).closest(".product-card").toggleClass("active")})},layerClose:function($productCard){$($productCard).find(".js-close").click(function(){$(this).closest(".product-card").removeClass("fav-in");$(this).closest(".product-card").removeClass("cart-in");$(this).closest(".product-card").removeClass("compare-in");$(this).closest(".product-card").removeClass("threeR-in")});$($productCard).mouseleave(function(){$(this).removeClass("fav-in");
$(this).removeClass("cart-in");$(this).removeClass("compare-in");$(this).removeClass("threeR-in")})},fav:function($fav){$($fav).click(function(){$(this).closest(".product-card").addClass("fav-in")})},cart:function($cart){$($cart).click(function(){$(this).closest(".product-card").addClass("cart-in")})},compare:function($compare){$($compare).click(function(){$(this).closest(".product-card").addClass("compare-in")})},threeR:function($threeR){$($threeR).click(function(){$(this).closest(".product-card").addClass("threeR-in")})}};
$(document).ready(function(){var $productCard=$(".product-card"),$fav=$(".js-fav"),$cart=$(".js-cart"),$compare=$(".js-compare"),$threeR=$(".js-threeR");try{$($productCard).each(function(i,e){productCard.layerClose(e)})}catch(error){console.log(error)}try{$($fav).each(function(i,e){productCard.fav(e)})}catch(error){console.log(error)}try{$($cart).each(function(i,e){productCard.cart(e)})}catch(error){console.log(error)}try{$($compare).each(function(i,e){productCard.compare(e)})}catch(error){console.log(error)}try{$($threeR).each(function(i,
e){productCard.threeR(e)})}catch(error){console.log(error)}try{$($productCard).each(function(i,e){productCard.activateCard(e)})}catch(error){console.log(error)}});
var productFilter={moveFiltersMobile:function($productFilter){var $menuList=$($productFilter).find(".js-menu-filters");var $dest=$($productFilter).find(".js-filters-mobile");var $items=$($menuList).detach();$($dest).append($items)},moveFiltersDesktop:function($productFilter){var $menuList=$($productFilter).find(".js-menu-filters");var $dest=$($productFilter).find(".js-filters-desktop");var $items=$($menuList).detach();$($dest).append($items)},changeColMobile:function($productFilter,$cardList){var $colButton=
$($productFilter).find(".js-change-cols-mobile");$($colButton).click(function(){$(this).toggleClass("active");$(this).closest("body").toggleClass("col-2-active");var $card=$($cardList).find(".product-card");$($card).css("height","auto");$($cardList).find(".product-card .title-producto").matchHeight();$($cardList).find(".product-card .colors").matchHeight();$($cardList).find(".product-card .dades").matchHeight();$($card).matchHeight()})},applySlider:function($jsSlider){$($jsSlider).not(".slick-initialized").slick({slidesToShow:7,
slidesToScroll:6,infinite:false,speed:300,dots:false,arrows:true,focusOnSelect:false,touchThreshold:10,responsive:[{breakpoint:1024,settings:{slidesToShow:5,slidesToScroll:4}},{breakpoint:992,settings:{arrows:false}},{breakpoint:640,settings:{slidesToShow:4,slidesToScroll:3,arrows:false}},{breakpoint:420,settings:{slidesToShow:2.75,slidesToScroll:2,arrows:false}}]})}};
$(document).ready(function(){var $productFilter=$(".product-filter"),cardList=$(".product-list"),$jsSlider=$(".category-filters").find(".js-slider"),windowWidth=$(window).width();try{$($jsSlider).each(function(i,e){productFilter.applySlider(e)})}catch(error){console.log(error)}try{$($productFilter).each(function(i,e){if(windowWidth<1025)productFilter.moveFiltersMobile(e);else productFilter.moveFiltersDesktop(e)})}catch(error){console.log(error)}try{$($productFilter).each(function(i,e){if(windowWidth<
1025)productFilter.changeColMobile(e,cardList)})}catch(error){console.log(error)}});$(window).resize(function(){var $productFilter=$(".product-filter"),cardList=$(".product-list"),windowWidth=$(window).width();try{$($productFilter).each(function(i,e){if(windowWidth<1025)productFilter.moveFiltersMobile(e);else productFilter.moveFiltersDesktop(e)})}catch(error){console.log(error)}try{$($productFilter).each(function(i,e){if(windowWidth<1025)productFilter.changeColMobile(e,cardList)})}catch(error){console.log(error)}});
var productList={cardHeight:function($cardList){var $card=$($cardList).find(".product-card");$($cardList).find(".product-card .title-producto").matchHeight();$($cardList).find(".product-card .colors").matchHeight();$($cardList).find(".product-card .dades").matchHeight();$($card).each(function(i,e){var cardHeight=$(e).height();$(e).css("height",cardHeight)})},orderMoveMobile:function(jsOrderMobile){var orderDetached=$(".order-selector__wrapper").detach();var $dest=$(jsOrderMobile);$(orderDetached).appendTo($dest)},
orderMoveDesktop:function(jsOrderDesktop){var orderDetached=$(".order-selector__wrapper").detach();var base=$(jsOrderDesktop);$(orderDetached).appendTo(base)}};
$(document).ready(function(){var cardList=$(".product-list"),jsOrderDesktop=$(".js-order-desktop"),jsOrderMobile=$(".js-order-mobile"),windowWidth=$(window).width();if(windowWidth<1025)try{productList.orderMoveMobile(jsOrderMobile)}catch(error){console.log(error)}else try{productList.orderMoveDesktop(jsOrderDesktop)}catch(error){console.log(error)}try{if(windowWidth>767)$(cardList).each(function(ind,el){productList.cardHeight(el)})}catch(error){console.log(error)}});
$(window).resize(function(){var cardList=$(".product-list"),jsOrderDesktop=$(".js-order-desktop"),jsOrderMobile=$(".js-order-mobile"),windowWidth=$(window).width();if(windowWidth<1025)try{productList.orderMoveMobile(jsOrderMobile)}catch(error){console.log(error)}else try{productList.orderMoveDesktop(jsOrderDesktop)}catch(error){console.log(error)}try{if(windowWidth>767)$(cardList).each(function(ind,el){productList.cardHeight(el)})}catch(error){console.log(error)}});
var lightbox={modalBasic:function(lightbox,lightboxModal){var $lightbox=$(lightbox);var $trigger=$($lightbox).closest(".has-modal").find('[data-toggle\x3d"modal"]');$trigger.click(function(){commons.closeRModals(".r-modal");var theModal=$(this).data("target");$(theModal).detach().appendTo("body");$(theModal).on("shown.bs.modal",function(e){});$(theModal).on("hidden.bs.modal",function(e){$(theModal).detach().appendTo(lightbox)});$(theModal).find(".js-close").click(function(){$(this).closest(".modal").modal("hide")})})},
modalVideo:function(lightbox,lightboxModal){var $lightbox=$(lightbox);var $trigger=$($lightbox).closest(".has-modal").find('[data-toggle\x3d"modal"]');$trigger.click(function(){commons.closeRModals(".r-modal");var theModal=$(this).data("target"),videoSRC=$(this).attr("data-theVideo"),videoSRCauto=videoSRC+"?rel\x3d0\x26autoplay\x3d1";if(!typeof videoSRC==="undefined")$(theModal+" iframe").attr("src",videoSRCauto).attr("allow","autoplay");$(theModal).detach().appendTo("body");$(theModal).on("hidden.bs.modal",
function(e){$(theModal+" iframe").attr("src",videoSRC);$(theModal).detach().appendTo(lightbox)});$(theModal).find(".js-close").click(function(){$(this).closest(".modal").modal("hide")})})},modalSlider:function(lightbox,lightboxModal){var $lightbox=$(lightbox);var $trigger=$($lightbox).closest(".has-modal").find('[data-toggle\x3d"modal"]');$trigger.click(function(){commons.closeRModals(".r-modal");var theModal=$(this).data("target"),videoSRC=$(this).attr("data-theVideo"),videoSRCauto=videoSRC+"?rel\x3d0\x26autoplay\x3d1";
$(theModal+" iframe").attr("src",videoSRCauto).attr("allow","autoplay");$(lightboxModal).detach().appendTo("body");$(theModal).on("hidden.bs.modal",function(e){$(theModal+" iframe").attr("src",videoSRC);$(lightboxModal).detach().appendTo(lightbox)});$(lightboxModal).find(".js-close").click(function(){$(this).closest(".modal").modal("hide")})})},modalSlick:function(lightbox,lightboxModal){var $lightbox=$(lightbox);var $trigger=$($lightbox).closest(".has-modal").find('[data-toggle\x3d"modal"]');$trigger.click(function(){commons.closeRModals(".r-modal");
var theModal=$(this).data("target");$(theModal).detach().appendTo("body");$(theModal).on("shown.bs.modal",function(e){$(theModal).find(".slider")[0].slick.refresh()});$(theModal).on("hidden.bs.modal",function(e){$(theModal).detach().appendTo(lightbox)});$(theModal).find(".js-close").click(function(){$(this).closest(".modal").modal("hide")})})},modalFilter:function(lightbox,lightboxModal){var $lightbox=$(lightbox);var $trigger=$($lightbox).closest(".has-modal").find('[data-toggle\x3d"modal"]');$trigger.click(function(){commons.closeRModals(".r-modal");
var theModal=$(this).data("target");$(theModal).detach().appendTo("body");$(theModal).on("shown.bs.modal",function(e){});$(theModal).on("hidden.bs.modal",function(e){$(theModal).detach().appendTo(lightbox)});$(theModal).find(".js-close").click(function(){var $modal=$(this).closest(".modal");$($modal).modal("hide")})})}};
$(document).ready(function(){var $lightboxBasic=$(".lightbox-basic-wrapper");var $lightboxSlider=$(".slick-slider").find(".lightbox-wrapper");var $lightbox=$(".lightbox-wrapper");var $lightboxSlicker=$(".lightbox-slick-wrapper");var $lightboxFilter=$(".lightbox-filter-wrapper");if($lightboxBasic.length>0)try{$lightboxBasic.each(function(i,e){var $lightboxModal=$(e).find(".modal");lightbox.modalBasic(e,$lightboxModal)})}catch(error){console.log("Try to set home lightbox got "+error)}if($lightboxSlider.length>
0)try{$lightboxSlider.each(function(i,e){var $lightboxModal=$(e).find(".modal");lightbox.modalSlider(e,$lightboxModal)})}catch(error){console.log("Try to set home lightbox got "+error)}try{$lightbox.each(function(i,e){var $lightboxModal=$(e).find(".modal");lightbox.modalVideo(e,$lightboxModal)})}catch(error){console.log("Try to set home lightbox got "+error)}try{$lightboxSlicker.each(function(i,e){var $lightboxModal=$(e).find(".modal");lightbox.modalSlick(e,$lightboxModal)})}catch(error){console.log("Try to set slick modal got "+
error)}try{$lightboxFilter.each(function(i,e){var $lightboxModal=$(e).find(".modal");lightbox.modalFilter(e,$lightboxModal)})}catch(error){console.log("Try to set slick modal got "+error)}});
var filters={sliderRangeInit:function($slider){var data=filters.sliderRangeData($slider);$($slider).find(".slider").slider({range:true,min:0,max:data.array.length-1,values:data.array,step:1,animate:true,orientation:"horizontal",slide:function(event,ui){$($slider).find(".min-input").val(ui.values[0]);$($slider).find(".max-input").val(ui.values[1]);$($slider).find(".min-range-d").html(data.array[ui.values[0]]);$($slider).find(".max-range-d").html(data.array[ui.values[1]])}});$($slider).find(".min-range-d").html(data.values[0]);
$($slider).find(".max-range-d").html(data.values[1]);$($slider).find(".min-range-text").html(data.min);$($slider).find(".max-range-text").html(data.max);$($slider).find(".slider").slider("option","values",[data.array.indexOf(data.values[0]),data.array.indexOf(data.values[1])])},sliderRangeData:function($slider){var sliderData={};sliderData.min=$($slider).find(".slider").data("min");sliderData.max=$($slider).find(".slider").data("max");sliderData.values=$($slider).find(".slider").data("values");sliderData.array=
$($slider).find(".slider").data("array");$($slider).find(".slider").slider();return sliderData},imageCheck:function($imageCheck){if($($imageCheck).find(".custom-control-input").is(":checked"))$($imageCheck).addClass("active");else $($imageCheck).removeClass("active");$($imageCheck).find(".custom-control-input").change(function(){if($(this).is(":checked"))$($imageCheck).addClass("active");else $($imageCheck).removeClass("active")})},numberCheck:function($numberCheck){if($($numberCheck).find(".custom-control-input").is(":checked"))$($numberCheck).addClass("active");
else $($numberCheck).removeClass("active");$($numberCheck).find(".custom-control-input").change(function(){if($(this).is(":checked"))$($numberCheck).addClass("active");else $($numberCheck).removeClass("active")})},categoryCheck:function($categoryCheck){if($($categoryCheck).find(".custom-control-input").is(":checked"))$($categoryCheck).addClass("active");else $($categoryCheck).removeClass("active");$($categoryCheck).find(".custom-control-input").change(function(){if($(this).is(":checked"))$($categoryCheck).addClass("active");
else $($categoryCheck).removeClass("active")})}};
$(document).ready(function(){var $slider=$(".slider-range"),$categoryCheck=$(".category-check"),$numberCheck=$(".number-check");try{if(typeof $slider!=="undefined")$($slider).each(function(){filters.sliderRangeInit(this)})}catch(error){console.log("Try to set SLider range got "+error)}try{if($categoryCheck.length>0)$($categoryCheck).each(function(){filters.categoryCheck(this)})}catch(error){console.log("Try to set category-check and got "+error)}try{if($numberCheck.length>0)$($numberCheck).each(function(){filters.numberCheck(this)})}catch(error){console.log("Try to set number-check and got "+
error)}});$(".open-product-bundle").click(function(){$(this).parent().find(".product-bundle-hidden-info").show();$(this).hide();$(this).parent().find(".close-product-bundle").show()});$(".close-product-bundle").click(function(){$(this).parent().find(".product-bundle-hidden-info").hide();$(this).hide();$(this).parent().find(".open-product-bundle").show()});$("#mostrar-texto").on("click",function(){$("#target-texto").show();$("#mostrar-texto").hide()});
$("#ocultar-texto").on("click",function(){$("#target-texto").hide();$("#mostrar-texto").show()});$("#mostrar").on("click",function(){$("#target").show();$("#mostrar").hide()});$("#ocultar").on("click",function(){$("#target").hide();$("#mostrar").show()});
$(function(){var mobileGallery=false;var windowWidth=$(window).width();if(windowWidth<=991)mobileGallery=true;if(mobileGallery){var swapLoad=false;$(".galeria-main-container").find(".view-more-btn").on("click",function(e){e.preventDefault();if(!swapLoad){$(".photo-galery:hidden").slice(0,1).fadeIn();$(".photo-galery-2:hidden").slice(0,2).fadeIn();swapLoad=true}else{$(".photo-galery:hidden").slice(0,2).fadeIn();$(".photo-galery-2:hidden").slice(0,1).fadeIn();swapLoad=false}if($(".photo-galery:hidden").length==
0&&$(".photo-galery-2:hidden").length==0)$(".galeria-main-container").find(".view-more-btn").fadeOut("slow")})}});
$(function(){var mobileGallery=false;var windowWidth=$(window).width();if(windowWidth<=991)mobileGallery=true;if(!mobileGallery)$(".galeria-main-container").find(".view-more-btn").on("click",function(e){e.preventDefault();var posTop=$(window).scrollTop();$(".photo-galery:hidden").slice(0,1).fadeIn();$(".photo-galery-2:hidden").slice(0,2).fadeIn();if($(".photo-galery:hidden").length==0)$(".galeria-main-container").find(".view-more-btn").fadeOut("slow");if($(".photo-galery-2:hidden").length==0)$(".galeria-main-container").find(".view-more-btn-end").fadeOut("slow");
else{$(this).fadeOut("slow");$(".galeria-main-container").find(".view-more-btn-end").fadeIn("slow")}var currentPosTop=$(window).scrollTop();while(currentPosTop!=posTop){window.scrollTo({top:posTop,left:0,behavior:"auto"});var currentPosTop=$(window).scrollTop()}})});
$(function(){var mobileGallery=false;var windowWidth=$(window).width();if(windowWidth<=991)mobileGallery=true;if(!mobileGallery)$(".galeria-main-container").find(".view-more-btn-end").on("click",function(e){e.preventDefault();var posTop=$(window).scrollTop();$(".photo-galery:hidden").slice(0,2).fadeIn();$(".photo-galery-2:hidden").slice(0,1).fadeIn();if($(".photo-galery:hidden").length==0)$(".galeria-main-container").find(".view-more-btn").fadeOut("slow");else{$(this).fadeOut("slow");$(".galeria-main-container").find(".view-more-btn").fadeIn("slow")}if($(".photo-galery-2:hidden").length==
0)$(".galeria-main-container").find(".view-more-btn-end").fadeOut("slow");var currentPosTop=$(window).scrollTop();while(currentPosTop!=posTop){window.scrollTo({top:posTop,left:0,behavior:"auto"});var currentPosTop=$(window).scrollTop()}})});$(function(){$("#imgdist-show-more").on("click",function(e){e.preventDefault();$(".image-wrapper:hidden").slice(0,11).fadeIn();if($(".image-wrapper:hidden").length==0)$("#imgdist-show-more").fadeOut("slow")})});$(document).ready(function(){$('[data-toggle\x3d"popover"]').popover()});
$(document).ready(function(){$("body").on("click",function(e){$("[data-toggle\x3dpopover]").each(function(){if(!$(this).is(e.target)&&$(this).has(e.target).length===0&&$(".popover").has(e.target).length===0)$(this).popover("hide")})})});$(document).ready(function(){$(".manualinputlabel").click(function(e){$(".popover-body").append('\x3cbutton id\x3d"popovercloseid" type\x3d"button" class\x3d"close"\x3e\x3c/button\x3e');$(this).popover()});$(document).click(function(e){if(e.target.id=="popovercloseid")$(".manualinputlabel").popover("hide")})});
$(document).ready(function(){$(".dropdown-toggle").dropdown()});
$(document).ready(function(){var $product=$(".wrapper-producto");var windowWidth=$(window).width();var device="desktop";if(windowWidth<768)device="mobile";function resultado(cajas){var precioCajas=parseFloat($(".js-precio-value span").text().split(",")[0]+"."+$(".js-precio-value span").text().split(",")[1]);var precio=cajas*precioCajas;var valor=precio.toString().split(".");var precioEntero=valor[0];var precioDecimal=valor[1].substr(0,2);$(".js-resultado .price").html(precioEntero+"\x3csub\x3e,"+
precioDecimal+" "+document.currencySymbol+"\x3c/sub")}function numCajas(superficie){var superficieCajas=parseFloat($(".js-superficie-value span").text().split(",")[0]+"."+$(".js-superficie-value span").text().split(",")[1]);var cajas=Math.ceil(superficie/superficieCajas);$(".js-calculadora input").val(cajas);resultado(cajas)}function superficie(cajas){var superficieCajas=parseFloat($(".js-superficie-value span").text().split(",")[0]+"."+$(".js-superficie-value span").text().split(",")[1]);var metros=
parseInt(cajas*superficieCajas);$(".js-superficie input").val(metros)}$(".js-calculadora input").keyup(function(){this.value=(this.value+"").replace(/[^0-9]/g,"");resultado(this.value);superficie(this.value)});$(".js-calculadora .less a").click(function(e){e.preventDefault();var value=$(".js-calculadora input").val();$(".js-calculadora input").val(parseInt(value)-1);resultado(parseInt(value)-1);superficie(parseInt(value)-1)});$(".js-calculadora .more a").click(function(e){e.preventDefault();var value=
$(".js-calculadora input").val();$(".js-calculadora input").val(parseInt(value)+1);resultado(parseInt(value)+1);superficie(parseInt(value)+1)});$(".js-superficie input").keyup(function(){this.value=(this.value+"").replace(/[^0-9]/g,"");numCajas(this.value)});if($(".capa-completa").length>0)$(".capa-scroll").niceScroll({cursorcolor:"#9a9a9a",cursorwidth:"3px",cursorborder:"none",background:"#d5d5d5",cursorborderradius:0,autohidemode:false,cursorminheight:60});if($(".accordion").length>0){$(".accordion li li a").click(function(){if(!$(this).hasClass("active"))$(".accordion li li a.active").removeClass("active");
$(".no-collapse").removeClass("active");$(this).closest(".subcategory").siblings("a").addClass("collapsed");$(this).toggleClass("active")});$(".accordion \x3e li \x3e a").click(function(){$(".no-collapse").removeClass("active");$(this).closest(".subcategory").siblings("a").addClass("collapsed");$(".accordion li li a.active").removeClass("active")});$(".no-collapse li a").click(function(){$(this).closest(".no-collapse").siblings("a").addClass("active")});$(".js-collapse-mobile-open").click(function(){$(".js-collapse-mobile").toggleClass("active");
$("body").toggleClass("noScroll")});$(".js-collapse-mobile-close").click(function(){$(".js-collapse-mobile").toggleClass("active");$("body").toggleClass("noScroll")})}$(document).ready(function(){var windowWidth=$(window).width();var faqItemTrigger=$(".faq-item__trigger");var faqItem=$(".faq-item");var faqList=$(".faq-list");if(faqList.length>0)if(windowWidth<992)faqItemTrigger.on("click",function(){if($(this).parent().hasClass("is-visible"))$(this).parent().removeClass("is-visible");else{$(".faq-item").removeClass("is-visible");
$(this).parent().addClass("is-visible")}})});$(window).resize(function(){$(".capa-scroll").getNiceScroll().resize()});try{if($(".js-slider-producto-5").length>0){$(".js-slider-producto-5").on("init",function(event,slick){product.applyMatchHeight($product);product.selectColor($product,device)});$(".js-slider-producto-5").on("reInit",function(event,slick){product.applyMatchHeight($product);product.selectColor($product,device)});$(".js-slider-producto-5").not(".slick-initialized").slick({dots:true,arrow:false,
slidesToShow:5,infinite:false,speed:300,responsive:[{breakpoint:1919,settings:{dots:true,slidesToShow:5}},{breakpoint:991,settings:{dots:false,slidesToShow:2}},{breakpoint:767,settings:{dots:false,slidesToShow:2}}]})}}catch(error){console.log("Try set slider product got "+error)}});
$(document).ready(function(){function onElementHeightChange(elm,callback){var lastHeight=elm.clientHeight,newHeight;(function run(){newHeight=elm.clientHeight;if(lastHeight!=newHeight)callback();lastHeight=newHeight;if(elm.onElementHeightChangeTimer)clearTimeout(elm.onElementHeightChangeTimer);elm.onElementHeightChangeTimer=setTimeout(run,200)})()}if($(".sales-filters").length>0){if($(window).width()>991){$(".column-height").niceScroll({cursorcolor:"#9a9a9a",cursorwidth:"5px",cursorborder:"none",
background:"#f7f7f7",railpadding:{top:0,left:6,bottom:0,right:3},cursorborderradius:0,autohidemode:false});$(".filters-acordeon").on("shown.bs.collapse hidden.bs.collapse",function(e){$(this).parent().parent().getNiceScroll().resize()})}$(window).resize(function(){if($(window).width()>991){$(".column-height").niceScroll({cursorcolor:"#9a9a9a",cursorwidth:"5px",cursorborder:"none",background:"#f7f7f7",railpadding:{top:0,left:6,bottom:0,right:3},cursorborderradius:0,autohidemode:false});$(".filters-acordeon").on("shown.bs.collapse hidden.bs.collapse",
function(e){$(this).parent().parent().niceScroll().resize()})}else $(".column-height").niceScroll().remove()})}onElementHeightChange(document.body,function(){if($(window).width()>991)$(".filters-acordeon").parent().parent().niceScroll().resize()})});
$(document).ready(function(){var windowWidth=$(window).width();if($(".sales-filters").length>0){function searchMobile(){if($(".sales-filters__map-search").find("button").length>0)$(".sales-filters__map-search").find("button").appendTo(".sales-filters__search");if($(".sales-filters__map-search").find("label").length>0)$(".sales-filters__map-search").find("label").appendTo(".sales-filters__search")}function searchDesktop(){if($(".sales-filters__search").find("button").length>0)$(".sales-filters__search").find("label").appendTo(".sales-filters__map-search");
if($(".sales-filters__search").find("button").length>0)$(".sales-filters__search").find("button").appendTo(".sales-filters__map-search")}function mapMobile(){if($(".sales-filters__map").find(".loader").length>0)$(".sales-filters__map").find(".loader").appendTo(".sales-filters-list__map");if($(".sales-filters__map").find("#map").length>0)$(".sales-filters__map").find("#map").appendTo(".sales-filters-list__map")}function mapDesktop(){if($(".sales-filters-list__map").find(".loader").length>0)$(".sales-filters-list__map").find(".loader").appendTo(".sales-filters__map");
if($(".sales-filters-list__map").find("#map").length>0)$(".sales-filters-list__map").find("#map").appendTo(".sales-filters__map")}if($(".sales-filters__search").length==0)$(".sales-filters__text").after('\x3cdiv class\x3d"sales-filters__search d-block d-lg-none"\x3e\x3c/div\x3e');if($(".sales-filters-list__map").length==0)$(".sales-filters__nosearch").after('\x3cdiv class\x3d"sales-filters-list__map d-block d-lg-none"\x3e\x3c/div\x3e');if(windowWidth<992){searchMobile();mapMobile()}$(window).resize(function(){var windowWidth=
$(window).width();if(windowWidth<992){searchMobile();mapMobile()}else{mapDesktop();searchDesktop()}})}});var userNav={setHeight:function($document,header,userAreaNav){var height=$($document).height()-$(header).height();$(userAreaNav).find(".user-area-nav__wrapper").height(height);var footer=$(userAreaNav).closest("body").find("footer");if(!$(footer).hasClass("isUserNav"))$(footer).addClass("isUserNav")}};
$(document).ready(function(){var $document=$(document),header=$("header"),userAreaNav=$(".user-area-nav");try{$(userAreaNav).each(function(i,e){var isEditable=$(e).closest(".portlet-content-editable").length;if(isEditable==0)userNav.setHeight($document,header,e)})}catch(error){console.log(error)}$(window).resize(function(){try{$(userAreaNav).each(function(i,e){var isEditable=$(e).closest(".portlet-content-editable").length;if(isEditable==0)userNav.setHeight($document,header,e)})}catch(error){console.log(error)}})});
var comparador={scroll:function($comparador,scrollPosition){var scrollAnchor=$($comparador).find(".scroll-slider").offset().top;if(scrollAnchor<scrollPosition)$($comparador).find(".scroll-slider").addClass("active");else $($comparador).find(".scroll-slider").removeClass("active")},filterSlideInit:function(filter,slideComparador,slideResume){var cat=$(filter).find(".nav-link.active").attr("data-category");if(cat!=="all"){$(slideComparador).slick("slickUnfilter");$(slideResume).slick("slickUnfilter");
$(slideComparador).find(".col").each(function(){$(this).removeClass("slide-shown")});$(slideResume).find(".col").each(function(){$(this).removeClass("slide-shown")});$(slideComparador).find(".col[data-match\x3d"+cat+"]").addClass("slide-shown");$(slideResume).find(".col[data-match\x3d"+cat+"]").addClass("slide-shown");$(slideComparador).slick("slickFilter",".slide-shown");$(slideResume).slick("slickFilter",".slide-shown")}},filterSlide:function(filter,slideComparador,slideResume){$(filter).find(".nav-link").click(function(){var cat=
$(this).attr("data-category");if(cat!=="all"){$(slideComparador).slick("slickUnfilter");$(slideResume).slick("slickUnfilter");$(slideComparador).find(".col").each(function(){$(this).removeClass("slide-shown")});$(slideResume).find(".col").each(function(){$(this).removeClass("slide-shown")});$(slideComparador).find(".col[data-match\x3d"+cat+"]").addClass("slide-shown");$(slideResume).find(".col[data-match\x3d"+cat+"]").addClass("slide-shown");$(slideComparador).slick("slickFilter",".slide-shown");
$(slideResume).slick("slickFilter",".slide-shown")}else{$(slideComparador).find(".col").each(function(){$(this).addClass("slide-shown")});$(slideComparador).slick("slickUnfilter");$(slideResume).find(".col").each(function(){$(this).addClass("slide-shown")});$(slideResume).slick("slickUnfilter")}})}};
$(document).ready(function(){var $resume=$(".resume-product");var $product=$(".wrapper-producto");var $tabsAgrupador=$("#tabs-agrupador");var $sliderComparador=$(".js-slider-producto-comparador");var $sliderResume=$(".js-slider-resume-comparador");$(window).scroll(function(){var scrollP=$(window).scrollTop();try{$(".comparador").each(function(i,e){comparador.scroll(e,scrollP)})}catch(error){console.log(error)}});try{if($(".js-slider-resume-comparador").length>0){var sliderProductCols=$(".js-slider-resume-comparador").data("col");
if($(window).width()<992&&$(window).width()>767)sliderProductCols=2;else if($(window).width()<768)sliderProductCols=1;$(".js-slider-resume-comparador").on("init",function(event,slick){product.applyMatchHeight($resume)});$(".js-slider-resume-comparador").on("reInit",function(event,slick){product.applyMatchHeight($resume)});$(".js-slider-resume-comparador").on("init reInit afterChange",function(event,slick,currentSlide,nextSlide){$(".slider-resume").find(".hidden-items-counter").text("+"+(slick.slideCount-
sliderProductCols));if(slick.slideCount-sliderProductCols<=0)$(".slider-resume").find(".hidden-items-counter").hide();else $(".slider-resume").find(".hidden-items-counter").show()});$(".js-slider-resume-comparador").not(".slick-initialized").slick({dots:false,arrow:true,speed:300,slidesToShow:sliderProductCols,asNavFor:".js-slider-producto-comparador",infinite:false,prevArrow:$(".prev-resume"),nextArrow:$(".next-resume"),responsive:[{breakpoint:1199,settings:{dots:false,slidesToShow:3}},{breakpoint:991,
settings:{dots:false,slidesToShow:2}},{breakpoint:767,settings:{dots:false,slidesToShow:1}}]}).on("setPosition",function(event,slick){slick.$slides.css("height",slick.$slideTrack.height()+"px")})}}catch(error){console.log("Try set slider resume got "+error)}try{if($(".js-slider-producto-comparador").length>0){var sliderProductCols=$(".js-slider-producto-comparador").data("col");if($(window).width()<992&&$(window).width()>767)sliderProductCols=2;else if($(window).width()<768)sliderProductCols=1;$(".js-slider-producto-comparador").on("init",
function(event,slick){product.applyMatchHeight($product)});$(".js-slider-producto-comparador").on("reInit",function(event,slick){product.applyMatchHeight($product)});$(".js-slider-producto-comparador").on("init reInit afterChange",function(event,slick,currentSlide,nextSlide){$(".slider-producto").find(".hidden-items-counter").text("+"+(slick.slideCount-sliderProductCols));if(slick.slideCount-sliderProductCols<=0)$(".slider-producto").find(".hidden-items-counter").hide();else $(".slider-producto").find(".hidden-items-counter").show()});
$(".js-slider-producto-comparador").not(".slick-initialized").slick({dots:false,arrow:true,slidesToShow:sliderProductCols,speed:300,asNavFor:".js-slider-resume-comparador",infinite:false,prevArrow:$(".prev-product"),nextArrow:$(".next-product"),responsive:[{breakpoint:1199,settings:{dots:false,slidesToShow:3}},{breakpoint:991,settings:{dots:false,slidesToShow:2}},{breakpoint:767,settings:{dots:false,slidesToShow:1}}]}).on("setPosition",function(event,slick){slick.$slides.css("height",slick.$slideTrack.height()+
"px")})}}catch(error){console.log("Try set slider product got "+error)}try{if($($tabsAgrupador).length>0)comparador.filterSlideInit($tabsAgrupador,$sliderComparador,$sliderResume)}catch(error){console.log(error)}try{if($($tabsAgrupador).length>0)comparador.filterSlide($tabsAgrupador,$sliderComparador,$sliderResume)}catch(error){console.log(error)}});var timeoutOverProduct=setTimeout(function(){$(".over-product").fadeOut(1500)},4E3);
function displayNotification(imageUrl,notificationContent,notificationType,linkUrl,linkText){if($(".over-product").length){$("#notif-img").empty();if(imageUrl){var imageEl='\x3cimg alt\x3d"" src\x3d"'+imageUrl+'"\x3e';$("#notif-img").append(imageEl)}$("#notif-content").empty();if(notificationContent)$("#notif-content").append(notificationContent);$("#notif-type").empty();if(notificationType)$("#notif-type").append(notificationType);$("#notif-url").empty();if(linkText)if(linkUrl){var url='\x3ca class\x3d"cta-square-black" href\x3d"'+
linkUrl+'"\x3e'+linkText+"\x3c/a\x3e";$("#notif-url").append(url)}else $("#notif-url").append(linkText)}else{var notification='\x3csection class\x3d"over-product" id\x3d"hidethis"\x3e'+'\x3cdiv class\x3d"jumbotron"\x3e\x3cdiv class\x3d"over-product__wrapper"\x3e'+'\x3cdiv class\x3d"row"\x3e\x3cdiv class\x3d"col-12 col-sm-6"\x3e'+'\x3cdiv class\x3d"row"\x3e\x3cdiv class\x3d"col-4"\x3e\x3cdiv class\x3d"image" id\x3d"notif-img"\x3e\x3c/div\x3e\x3c/div\x3e'+'\x3cdiv class\x3d"col-8"\x3e\x3cdiv class\x3d"wrapper-text" id\x3d"notif-content"\x3e\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e'+
'\x3cdiv class\x3d"col-12 col-sm-6 d-flex align-items-center justify-content-md-end"\x3e'+'\x3cdiv class\x3d"row  align-items-center justify-content-md-end"\x3e'+'\x3cp class\x3d"btnReset addfav" id\x3d"notif-type"\x3e\x3c/p\x3e'+'\x3cp class\x3d"verfav" id\x3d"notif-url"\x3e\x3c/p\x3e'+"\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e\x3c/section\x3e";$("body").append(notification);if(imageUrl){var notificationImage='\x3cimg alt\x3d"" src\x3d"'+imageUrl+'"\x3e';$("#notif-img").append(notificationImage)}if(notificationContent)$("#notif-content").append(notificationContent);
if(notificationType)$("#notif-type").append(notificationType);if(linkText)if(linkUrl){var notificationUrl='\x3ca class\x3d"cta-square-black" href\x3d"'+linkUrl+'"\x3e'+linkText+"\x3c/a\x3e";$("#notif-url").append(notificationUrl)}else $("#notif-url").append(linkText)}$(".over-product").stop().fadeOut();$(".over-product").fadeIn(300);timeoutOverProduct=clearTimeout(timeoutOverProduct);timeoutOverProduct=setTimeout(function(){$(".over-product").fadeOut(1500)},4E3)}
$(document).ready(function(){var $html=$(".html-base");var $htmlTable=$(".html-base").find("table");if(typeof $htmlTable!=="undefined")$(".html-base").find("table").each(function(){var htmlClone=$(this).clone();$(this).wrap("\x3cdiv class\x3d'table-responsive'\x3e\x3c/div\x3e")})});
function setCookie(cname,cvalue,exdays){var date=new Date;if(exdays>0)date.setTime(date.getTime()+days*24*60*60*1E3);else date.setFullYear(date.getFullYear()+1);document.cookie=cname+"\x3d"+cvalue+";expires\x3d"+date.toUTCString()+";path\x3d/"}
function getCookie(cname){var name=cname+"\x3d";var decodedCookie=decodeURIComponent(document.cookie);var ca=decodedCookie.split(";");for(var i=0;i<ca.length;i++){var c=ca[i];while(c.charAt(0)===" ")c=c.substring(1);if(c.indexOf(name)===0)return c.substring(name.length,c.length)}return""}
$("document").ready(function(){if(getCookie("cpolicy").length==0)$(".cookie-warn").toggleClass("active");$(".close-cookie").on("click",function(e){e.preventDefault();$(".cookie-warn").hide();setCookie("cpolicy","true",0)});if(getCookie("apptop").length==0)if(/Android/i.test(navigator.userAgent)){$("#phone-popup").toggleClass("active");$("#dl-app-url").attr("href","https://play.google.com/store/apps/details?id\x3dnet.roca.rocacatalog")}else if(/iPhone|iPad/i.test(navigator.userAgent)){$("#phone-popup").toggleClass("active");
$("#dl-app-url").attr("href","https://apps.apple.com/es/app/roca-product-catalogue/id579584692")}$(".popup-app").find(".js-close").click(function(){$(this).closest(".popup-app").removeClass("active");setCookie("apptop","true",0)});try{var promoHeight=$(".promoSubmenu").children().first().height();var userMenu=$(".user-menu-mobile").height();var subMenuBar=$(".menus-secundarios").height();var pestanas=$(".menu-pestanas").height();$(window).scroll(function(){var scroll=$(window).scrollTop();var limit=
scroll;if(promoHeight)limit+=promoHeight;else promoHeight=0;if(userMenu)limit+=userMenu;else userMenu=0;if(subMenuBar)limit+=subMenuBar;else subMenuBar=0;if(pestanas)limit+=pestanas;else pestanas=0;if($(".menu-anclas.white-theme").length>0)if(userMenu&&userMenu>0){if($(".menu-anclas.white-theme").offset().top<=limit)if(userMenu&&userMenu>0){$(".menu-anclas.white-theme").css("position","fixed");$(".menu-anclas.white-theme").css("top",promoHeight+userMenu)}else $(".menu-anclas.white-theme").css("position",
"relative")}else if(!userMenu)if($(".menu-anclas.white-theme").offset().top<=limit){$(".menu-anclas.white-theme").css("position","fixed");$(".menu-anclas.white-theme").css("top",promoHeight)}else $(".menu-anclas.white-theme").css("position","relative");if($(".menus-secundarios").length>0)if($(".menus-secundarios").offset().top<limit)if($(".menus-secundarios").closest(".js-submenu").hasClass("menu-fixed")){$(".menus-secundarios").css("position","fixed");$(".menus-secundarios").css("top",promoHeight+
userMenu)}else $(".menus-secundarios").css("position","relative");else $(".menus-secundarios").css("position","relative");if($(".product-filter").length>0&&$(window).width()<993)if($(".product-filter").offset().top<limit)if($(".product-filter").closest(".row").hasClass("mobile-fixed"))if($("body").hasClass("has-control-menu")){$(".product-filter").css("position","fixed");$(".product-filter").css("top","56px");$(".product-filter").css("left","0");$(".product-filter").css("z-index","99")}else{$(".product-filter").css("position",
"fixed");$(".product-filter").css("top","0");$(".product-filter").css("left","0");$(".product-filter").css("z-index","99")}else{$(".product-filter").css("position","relative");$(".product-filter").css("top","0");$(".product-filter").css("left","0")}else{$(".product-filter").css("position","relative");$(".product-filter").css("top","0");$(".product-filter").css("left","0")}if($(".menu-pestanas").length>0)if($(".menu-pestanas").offset().top<limit)if($(".menu-pestanas").closest(".js-submenu").hasClass("menu-fixed")){$(".menu-pestanas").css("position",
"fixed");$(".menu-pestanas").css("top",promoHeight+userMenu+subMenuBar)}else $(".menu-pestanas").css("position","relative");else $(".menu-pestanas").css("position","relative")})}catch(error){console.log(error)}});
$(document).ready(function(){try{if($(".js-slider-sku").length>0)$(".js-slider-sku").each(function(i,slider){let sliderSkuCols=$(slider).data("col");if($(window).width()>767)sliderSkuCols=3;else if($(window).width()<768)sliderSkuCols=1;$(slider).slick({dots:true,arrow:false,slidesToShow:sliderSkuCols,infinite:false,speed:300,touchThreshold:10,centerMode:false,slidesToScroll:2,responsive:[{breakpoint:1199,settings:{dots:true,slidesToShow:3}},{breakpoint:991,settings:{dots:true,slidesToShow:2,slidesToScroll:1}},
{breakpoint:767,settings:"unslick"}]}).on("setPosition",function(event,slick){slick.$slides.css("height",slick.$slideTrack.height()+"px")})})}catch(error){console.log("Sku product: "+error)}});